services:
  nats:
    image: nats:2-alpine
    ports:
      - "4222:4222"

  inventory-service:
    build: ./inventory-service
    environment:
      NATS_URL: nats://nats:4222
    depends_on:
      - nats

  order-service:
    build: ./order-service
    environment:
      NATS_URL: nats://nats:4222
    depends_on:
      - nats
